name: simpsons
description: Une app Android Flutter pour explorer les Simpsons.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.0
  flutter_secure_storage: ^8.1.0
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
