name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get
        working-directory: simpsons

      - name: Analyze project source
        run: flutter analyze
        working-directory: simpsons

      - name: Run tests
        run: flutter test
        working-directory: simpsons

      - name: Build APK
        run: flutter build apk --release
        working-directory: simpsons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: simpsons/build/app/outputs/flutter-apk/app-release.apk

      - name: Build Web
        run: flutter build web --release
        working-directory: simpsons

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-web
          path: simpsons/build/web
